// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using boilerplate.api.data;

#nullable disable

namespace boilerplate.api.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211128120527_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("boilerplate.api.data.Models.Musician", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTimeOffset>("DateCreated")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<DateTimeOffset>("DateModified")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<string>("Name")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("");

                b.HasKey("Id");

                b.ToTable("Musicians", "dbo");
            });

            modelBuilder.Entity("boilerplate.api.data.Models.MusicLabel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTimeOffset>("DateCreated")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<DateTimeOffset>("DateModified")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<string>("Name")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("");

                b.HasKey("Id");

                b.ToTable("MusicLabels", "dbo");
            });

            modelBuilder.Entity("boilerplate.api.data.Models.Platform", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTimeOffset>("DateCreated")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<DateTimeOffset>("DateModified")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<string>("Name")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue("");

                b.HasKey("Id");

                b.ToTable("Platforms", "dbo");
            });

            modelBuilder.Entity("boilerplate.api.data.Models.ProcedureVersion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTimeOffset>("DateCreated")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<DateTimeOffset>("DateModified")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset")
                    .HasDefaultValueSql("(SYSDATETIMEOFFSET())");

                b.Property<string>("ProcedureName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Version")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("ProcedureVersions", "dbo");
            });
#pragma warning restore 612, 618
        }
    }
}